# Generated by Django 4.2 on 2023-04-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("talvido_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="talvidouser",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Username",
            ),
        ),
    ]
