# Generated by Django 4.2 on 2023-04-14 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("talvido_app", "0002_alter_talvidouser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="talvidouser",
            name="mobile_number",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
                verbose_name="Mobile Number",
            ),
        ),
    ]
