# Generated by Django 4.2 on 2023-04-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("talvido_app", "0003_alter_talvidouser_mobile_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="talvidouser",
            name="login_with",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Mobile Number", "Mobile Number"),
                    ("Google", "Google"),
                    ("Facebook", "Facebook"),
                ],
                default="",
                max_length=100,
                null=True,
                verbose_name="Login with",
            ),
        ),
    ]
