# Generated by Django 4.2 on 2023-04-29 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("talvido_app", "0004_postcommentlike"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("POST_LIKE", "POST_LIKE"),
                            ("POST_COMMENT", "POST_COMMENT"),
                            ("POST_COMMENT_LIKE", "POST_COMMENT_LIKE"),
                        ],
                        max_length=100,
                        verbose_name="Notification Type",
                    ),
                ),
                (
                    "post_comment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="talvido_app.postcomment",
                        verbose_name="Post Comment",
                    ),
                ),
                (
                    "post_comment_like",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="talvido_app.postcommentlike",
                        verbose_name="Post Comment Like",
                    ),
                ),
                (
                    "post_like",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="talvido_app.postlike",
                        verbose_name="Post Like",
                    ),
                ),
                (
                    "user_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_user_from",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User From",
                    ),
                ),
                (
                    "user_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_user_to",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User To",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
