# Generated by Django 4.2 on 2023-04-29 09:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("talvido_app", "0008_reelcomment_reellike_reelcommentlike"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reellike",
            unique_together={("user", "reel")},
        ),
    ]
