# Generated by Django 4.2 on 2023-04-29 11:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("talvido_app", "0007_storyhighlight"),
        ("talvido_app", "0009_alter_reellike_unique_together"),
    ]

    operations = []
