# Generated by Django 4.2 on 2023-05-01 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("talvido_app", "0010_merge_20230429_1145"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReelView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("views", models.IntegerField(default=0, verbose_name="Reel Views")),
                (
                    "reel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reel_view_reel",
                        to="talvido_app.reel",
                        verbose_name="Reel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
