# Generated by Django 4.2 on 2023-05-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("talvido_app", "0011_reelview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reel",
            name="reel",
            field=models.FileField(upload_to="reel/", verbose_name="Reel"),
        ),
    ]
