# Generated by Django 4.2 on 2023-04-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("talvido_app", "0011_postcomment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="talvidouser",
            name="full_name",
        ),
        migrations.AddField(
            model_name="talvidouser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AddField(
            model_name="talvidouser",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
    ]
