# Generated by Django 4.2 on 2023-05-08 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("talvido_app", "0012_alter_reel_reel"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "bank_name",
                    models.CharField(max_length=100, verbose_name="Bank Name"),
                ),
                (
                    "account_number",
                    models.CharField(max_length=100, verbose_name="Account Number"),
                ),
                (
                    "ifsc_code",
                    models.CharField(max_length=100, verbose_name="IFSC Code"),
                ),
                (
                    "account_holder_name",
                    models.CharField(
                        max_length=100, verbose_name="Account Holder Name"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
