# Generated by Django 4.2 on 2023-04-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "talvido_app",
            "0012_remove_talvidouser_full_name_talvidouser_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "MALE"), ("FEMALE", "FEMALE"), ("OTHER", "OTHER")],
                max_length=100,
                verbose_name="Gender",
            ),
        ),
    ]
