# Generated by Django 4.2 on 2023-05-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("talvido_app", "0014_bankpayment"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyPaymentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=100, verbose_name="Display Name")),
                (
                    "qrcode",
                    models.ImageField(upload_to="qrcode/", verbose_name="QRCode"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
