# Generated by Django 4.2 on 2023-05-11 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("talvido_app", "0017_recentaccountsearch"),
    ]

    operations = [
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("level", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=200)),
                ("min_points", models.IntegerField(verbose_name="Minimum point")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="levels/", verbose_name="Image"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PointSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "activity",
                    models.CharField(
                        choices=[
                            ("Time Spends", "Time Spends"),
                            ("Referral", "Referral"),
                            ("Share", "Share"),
                            ("Comments", "Comments"),
                            ("Like", "Like"),
                        ],
                        unique=True,
                        verbose_name="User Activity",
                    ),
                ),
                ("count", models.IntegerField(verbose_name="Activity Perform Count")),
                (
                    "points",
                    models.FloatField(
                        help_text="Point will be added on user points when user perform activity on\n        given Activity Perform Count.",
                        verbose_name="Points",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
                (
                    "validity",
                    models.CharField(
                        choices=[("1", "1"), ("3", "3"), ("6", "6"), ("12", "12")],
                        default="12",
                        max_length=2,
                        verbose_name="Validity In Months",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="subscription-image/"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="talvidouser",
            name="referral_code",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                unique=True,
                verbose_name="Referral Code",
            ),
        ),
        migrations.CreateModel(
            name="ReferralUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "referral_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_by_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Refered by User",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Joined User",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Point",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "activity",
                    models.CharField(
                        choices=[
                            ("Time Spends", "Time Spends"),
                            ("Referral", "Referral"),
                            ("Share", "Share"),
                            ("Comments", "Comments"),
                            ("Like", "Like"),
                        ],
                        verbose_name="User Activity",
                    ),
                ),
                ("points", models.FloatField(verbose_name="Points")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_point",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
