# Generated by Django 4.2 on 2023-05-10 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("talvido_app", "0018_subscription_alter_talvidouser_referral_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="validity",
            field=models.CharField(
                choices=[("1", "1"), ("3", "3"), ("6", "6"), ("12", "12")],
                default="12",
                max_length=2,
                verbose_name="Validity In Months",
            ),
        ),
        migrations.CreateModel(
            name="ReferralUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "referral_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_by_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Refered by User",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Joined User",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
