# Generated by Django 4.2 on 2023-05-11 09:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("talvido_app", "0018_level_pointsetting_subscription_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="point",
            name="user",
        ),
        migrations.DeleteModel(
            name="PointSetting",
        ),
        migrations.DeleteModel(
            name="Point",
        ),
    ]
