# Generated by Django 4.1.5 on 2023-05-11 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("talvido_app", "0019_remove_point_user_delete_pointsetting_delete_point"),
    ]

    operations = [
        migrations.CreateModel(
            name="PointSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "activity",
                    models.CharField(
                        choices=[
                            ("Time Spends", "Time Spends"),
                            ("Referral", "Referral"),
                            ("Share", "Share"),
                            ("Comments", "Comments"),
                            ("Like", "Like"),
                        ],
                        max_length=100,
                        unique=True,
                        verbose_name="User Activity",
                    ),
                ),
                ("count", models.IntegerField(verbose_name="Activity Perform Count")),
                (
                    "points",
                    models.FloatField(
                        help_text="Point will be added on user points when user perform activity on\n        given Activity Perform Count.",
                        verbose_name="Points",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Point",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("points", models.FloatField(verbose_name="Points")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_point",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
