# Generated by Django 4.2 on 2023-05-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("talvido_app", "0020_level_pointsetting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pointsetting",
            name="points",
            field=models.IntegerField(
                help_text="Point will be added on user points when user perform activity on\n        given Activity Perform Count.",
                verbose_name="Points",
            ),
        ),
    ]
