# Generated by Django 4.2 on 2023-05-11 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("talvido_app", "0020_pointsetting_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="point",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_point",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
