# Generated by Django 4.2 on 2023-05-11 08:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("talvido_app", "0020_level"),
        ("talvido_app", "0020_level_pointsetting"),
    ]

    operations = []
